### ISSUE TITLE
Documentation 3.0 issues 

### ISSUE THREAD

**Issue by sgauruseu** [enonic/nextxp-demo#888]
-  **Next.js setup topic** -  the json data in the screenshots in the guide does not match the actual json data (displayName, dataAsJson)

 - **Live deployment  topic** - `Create a new route`  should be replaced with `create new Ingress`:
 
 
![image](https://github.com/enonic/nextxp-demo/assets/3728712/0644251e-7885-4435-a787-636d38c7b40d)

**Comment by pmi** [comment]
Would be nice if you could include *actual json data* @sgauruseu
