### ISSUE TITLE
Problems with the new "rich text" chapter

### ISSUE THREAD

**Issue by sigdestad** [enonic/nextxp-demo#959]
* Rich text chapter should be placed before "custom pages" - as it is not related to page rendering
* It would be nice to have some links to the XP docs (and possibly dev 101) that explain more details on RichText
* Drop mentioning the "text component" - it only causes confusion
* Drop "To do it we need to follow 3 simple steps:" section - only causes confusion
* It says to convert bio from text to htmlArea - but it is already htmlArea?
* Tasks must be marked as tasks (like the other chapters)
* The macro chapter needs more info, it is really hard to understand what is going on there? How about a task here as well?

**Comment by pmi** [comment]
### Disagree on the following points:
- 3 steps is an overview of what needs to be done and helps understanding
- Making sure that the content type field is converted to html area is crucial and removing that will render users unable to convert any other arbitrary field!

**Comment by sigdestad** [comment]
It would make sense if this is what the user will do, but AFAIK, the field is already HtmlArea in this case.
It is important that this chapter looks and feels like the other chapters, it does not live on its own.

It is also important that our demo contains the RichText rendering by default, as this is the end result of the tutorial.
